// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connection_of_`, `connection_summary_`, `current_`, `describe_client_error_`, `lock_`, `view_of_`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 三种连接方式的 `kind` 取值（界面用它填下拉框）。
///
/// 顺序就是建议的展示顺序：先本机、后远程。
Future<List<String>> connectionKinds() =>
    RustLib.instance.api.crateApiKbConnectionKinds();

/// 某种连接方式的说明（界面上的提示文案）。
Future<String> connectionKindDescription({required String kind}) =>
    RustLib.instance.api.crateApiKbConnectionKindDescription(kind: kind);

/// 配置文件的路径。
Future<String> configFilePath() =>
    RustLib.instance.api.crateApiKbConfigFilePath();

/// 读配置。
///
/// 文件不存在时返回 `exists == false` 且 `error` 为空——**这不是错误**：
/// 界面据此进入"首次运行"，让用户选择或填写连接方式，再用 [`save_config`] 写出去。
Future<ConfigView> loadConfig() => RustLib.instance.api.crateApiKbLoadConfig();

/// 写配置（首次生成，或者用户改完之后保存）。
///
/// 返回空串表示成功，否则是失败说明。
Future<String> saveConfig({
  required String defaultName,
  required List<ConnectionView> connections,
}) => RustLib.instance.api.crateApiKbSaveConfig(
  defaultName: defaultName,
  connections: connections,
);

/// 首次运行时给界面一个**预填**的本机连接方式。
///
/// `kb_core` 的路径是"猜"出来的（与本可执行文件同目录），Flutter 打包出来的 App
/// 里通常猜不到——那时它是空串，界面必须让用户自己选。
Future<ConnectionView> suggestedLocalConnection({required String name}) =>
    RustLib.instance.api.crateApiKbSuggestedLocalConnection(name: name);

/// 连上 `kb_core`（系统层 + 应用层握手）。
///
/// 成功后，[`list_workspaces`] / [`list_sessions`] 就用这条连接；再连一次会
/// 替换掉旧的（旧的被丢弃时，如果是本机启动方式，它起的 `kb_core` 也会被结束）。
Future<ConnectReport> connectTo({required ConnectionView profile}) =>
    RustLib.instance.api.crateApiKbConnectTo(profile: profile);

/// 断开当前连接（本机启动方式会把那个 `kb_core` 子进程结束掉）。
Future<void> disconnect() => RustLib.instance.api.crateApiKbDisconnect();

/// 现在连的是谁。
Future<ConnectionState> connectionState() =>
    RustLib.instance.api.crateApiKbConnectionState();

/// 列出当前连接下的全部工作区。
Future<WorkspacesReport> listWorkspaces() =>
    RustLib.instance.api.crateApiKbListWorkspaces();

/// 列出某个工作区下的会话（只有摘要）。
Future<SessionsReport> listSessions({required String workspaceId}) =>
    RustLib.instance.api.crateApiKbListSessions(workspaceId: workspaceId);

/// 配置文件的快照。
class ConfigView {
  /// 配置文件路径（界面上显示出来，方便用户手改）。
  final String path;

  /// 文件是不是存在。`false` 表示**首次运行**：界面应当引导用户新建。
  final bool exists;

  /// 缺省用哪条连接方式的名字（可能为空）。
  final String defaultName;

  /// 已配置的连接方式。
  final List<ConnectionView> connections;

  /// 读取 / 解析失败的说明；空串表示没问题。
  ///
  /// 注意与 `exists == false` 的区别：文件在、但内容坏了时 `exists == true`
  /// 而 `error` 非空——界面应当让用户去修，而不是当成首次运行覆盖掉。
  final String error;

  const ConfigView({
    required this.path,
    required this.exists,
    required this.defaultName,
    required this.connections,
    required this.error,
  });

  static Future<ConfigView> default_() =>
      RustLib.instance.api.crateApiKbConfigViewDefault();

  @override
  int get hashCode =>
      path.hashCode ^
      exists.hashCode ^
      defaultName.hashCode ^
      connections.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigView &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          exists == other.exists &&
          defaultName == other.defaultName &&
          connections == other.connections &&
          error == other.error;
}

/// 一次连接的尝试结果。
class ConnectReport {
  /// 是否连上（含应用层握手成功）。
  final bool ok;

  /// 用的是哪条连接方式。
  final String profileName;

  /// 服务端版本（握手拿到的）。
  final String serverVersion;

  /// 协议版本（握手拿到的）。
  final int protocolVersion;

  /// 是不是本机连接（IPC）而不是远程 TCP。
  final bool isLocal;

  /// 客户端自己起的 `kb_core` 的 pid；附着 / 远程连接是 `0`。
  final int launchedPid;

  /// 失败的说明；空串表示成功。
  final String error;

  const ConnectReport({
    required this.ok,
    required this.profileName,
    required this.serverVersion,
    required this.protocolVersion,
    required this.isLocal,
    required this.launchedPid,
    required this.error,
  });

  static Future<ConnectReport> default_() =>
      RustLib.instance.api.crateApiKbConnectReportDefault();

  @override
  int get hashCode =>
      ok.hashCode ^
      profileName.hashCode ^
      serverVersion.hashCode ^
      protocolVersion.hashCode ^
      isLocal.hashCode ^
      launchedPid.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectReport &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          profileName == other.profileName &&
          serverVersion == other.serverVersion &&
          protocolVersion == other.protocolVersion &&
          isLocal == other.isLocal &&
          launchedPid == other.launchedPid &&
          error == other.error;
}

/// 当前连接的状态（给界面显示"现在连的是谁"）。
class ConnectionState {
  /// 现在有没有连上。
  final bool connected;

  /// 用的是哪条连接方式。
  final String profileName;

  /// 服务端版本。
  final String serverVersion;

  /// 客户端自己起的 `kb_core` 的 pid；没有则是 `0`。
  final int launchedPid;

  const ConnectionState({
    required this.connected,
    required this.profileName,
    required this.serverVersion,
    required this.launchedPid,
  });

  static Future<ConnectionState> default_() =>
      RustLib.instance.api.crateApiKbConnectionStateDefault();

  @override
  int get hashCode =>
      connected.hashCode ^
      profileName.hashCode ^
      serverVersion.hashCode ^
      launchedPid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionState &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          profileName == other.profileName &&
          serverVersion == other.serverVersion &&
          launchedPid == other.launchedPid;
}

/// 一条连接方式的扁平视图。
///
/// 三种 `kind` 共用这一个结构体（不适用的字段留空），这样界面只需要处理一种
/// 行、FRB 也只需要镜像一个类型。`kind` 的取值见 [`connection_kinds`]。
class ConnectionView {
  /// 界面上显示的名字，也是 `default` 引用的键。
  final String name;

  /// 种类：`local-launch` / `local-attach` / `tcp`。
  final String kind;

  /// 一行人类可读的说明（界面上一眼看出"连的是什么"）。
  final String summary;

  /// `local-launch`：`kb_core` 可执行文件路径。
  final String kbCore;

  /// `local-launch` / `local-attach`：运行时目录。
  final String runtimeDir;

  /// `local-launch`：存储目录。
  final String storageDir;

  /// `tcp`：`主机:端口`。
  final String address;

  const ConnectionView({
    required this.name,
    required this.kind,
    required this.summary,
    required this.kbCore,
    required this.runtimeDir,
    required this.storageDir,
    required this.address,
  });

  static Future<ConnectionView> default_() =>
      RustLib.instance.api.crateApiKbConnectionViewDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      kind.hashCode ^
      summary.hashCode ^
      kbCore.hashCode ^
      runtimeDir.hashCode ^
      storageDir.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          summary == other.summary &&
          kbCore == other.kbCore &&
          runtimeDir == other.runtimeDir &&
          storageDir == other.storageDir &&
          address == other.address;
}

/// 一个会话（只有摘要）。
class SessionView {
  /// 会话标识。
  final String id;

  /// 所属工作区标识。
  final String workspaceId;

  /// 标题。
  final String title;

  /// 最近活动时间（自 Unix 纪元起的毫秒数）。
  final PlatformInt64 updatedAtMillis;

  /// 该会话里已有的回合数。
  final int turnCount;

  const SessionView({
    required this.id,
    required this.workspaceId,
    required this.title,
    required this.updatedAtMillis,
    required this.turnCount,
  });

  static Future<SessionView> default_() =>
      RustLib.instance.api.crateApiKbSessionViewDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      title.hashCode ^
      updatedAtMillis.hashCode ^
      turnCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          title == other.title &&
          updatedAtMillis == other.updatedAtMillis &&
          turnCount == other.turnCount;
}

/// 列会话的结果。
class SessionsReport {
  /// 是否成功。
  final bool ok;

  /// 会话列表（失败时为空）。
  final List<SessionView> sessions;

  /// 失败的说明；空串表示成功。
  final String error;

  const SessionsReport({
    required this.ok,
    required this.sessions,
    required this.error,
  });

  static Future<SessionsReport> default_() =>
      RustLib.instance.api.crateApiKbSessionsReportDefault();

  @override
  int get hashCode => ok.hashCode ^ sessions.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionsReport &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          sessions == other.sessions &&
          error == other.error;
}

/// 一个工作区。
class WorkspaceView {
  /// 工作区标识（`kb_core` 分配）。
  final String id;

  /// 展示名。
  final String name;

  /// 对应的磁盘目录。
  final String path;

  const WorkspaceView({
    required this.id,
    required this.name,
    required this.path,
  });

  static Future<WorkspaceView> default_() =>
      RustLib.instance.api.crateApiKbWorkspaceViewDefault();

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          path == other.path;
}

/// 列工作区的结果。
class WorkspacesReport {
  /// 是否成功。
  final bool ok;

  /// 工作区列表（失败时为空）。
  final List<WorkspaceView> workspaces;

  /// 失败的说明；空串表示成功。
  final String error;

  const WorkspacesReport({
    required this.ok,
    required this.workspaces,
    required this.error,
  });

  static Future<WorkspacesReport> default_() =>
      RustLib.instance.api.crateApiKbWorkspacesReportDefault();

  @override
  int get hashCode => ok.hashCode ^ workspaces.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspacesReport &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          workspaces == other.workspaces &&
          error == other.error;
}
