// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/kb.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConnectionView dco_decode_box_autoadd_connection_view(dynamic raw);

  @protected
  ConfigView dco_decode_config_view(dynamic raw);

  @protected
  ConnectReport dco_decode_connect_report(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  ConnectionView dco_decode_connection_view(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConnectionView> dco_decode_list_connection_view(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionView> dco_decode_list_session_view(dynamic raw);

  @protected
  List<TurnView> dco_decode_list_turn_view(dynamic raw);

  @protected
  List<WorkspaceView> dco_decode_list_workspace_view(dynamic raw);

  @protected
  OpReport dco_decode_op_report(dynamic raw);

  @protected
  SessionDetailReport dco_decode_session_detail_report(dynamic raw);

  @protected
  SessionReport dco_decode_session_report(dynamic raw);

  @protected
  SessionView dco_decode_session_view(dynamic raw);

  @protected
  SessionsReport dco_decode_sessions_report(dynamic raw);

  @protected
  TurnView dco_decode_turn_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceReport dco_decode_workspace_report(dynamic raw);

  @protected
  WorkspaceView dco_decode_workspace_view(dynamic raw);

  @protected
  WorkspacesReport dco_decode_workspaces_report(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConnectionView sse_decode_box_autoadd_connection_view(
    SseDeserializer deserializer,
  );

  @protected
  ConfigView sse_decode_config_view(SseDeserializer deserializer);

  @protected
  ConnectReport sse_decode_connect_report(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  ConnectionView sse_decode_connection_view(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConnectionView> sse_decode_list_connection_view(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionView> sse_decode_list_session_view(SseDeserializer deserializer);

  @protected
  List<TurnView> sse_decode_list_turn_view(SseDeserializer deserializer);

  @protected
  List<WorkspaceView> sse_decode_list_workspace_view(
    SseDeserializer deserializer,
  );

  @protected
  OpReport sse_decode_op_report(SseDeserializer deserializer);

  @protected
  SessionDetailReport sse_decode_session_detail_report(
    SseDeserializer deserializer,
  );

  @protected
  SessionReport sse_decode_session_report(SseDeserializer deserializer);

  @protected
  SessionView sse_decode_session_view(SseDeserializer deserializer);

  @protected
  SessionsReport sse_decode_sessions_report(SseDeserializer deserializer);

  @protected
  TurnView sse_decode_turn_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceReport sse_decode_workspace_report(SseDeserializer deserializer);

  @protected
  WorkspaceView sse_decode_workspace_view(SseDeserializer deserializer);

  @protected
  WorkspacesReport sse_decode_workspaces_report(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_connection_view(
    ConnectionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_view(ConfigView self, SseSerializer serializer);

  @protected
  void sse_encode_connect_report(ConnectReport self, SseSerializer serializer);

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_view(
    ConnectionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_connection_view(
    List<ConnectionView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_view(
    List<SessionView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_turn_view(List<TurnView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_workspace_view(
    List<WorkspaceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_op_report(OpReport self, SseSerializer serializer);

  @protected
  void sse_encode_session_detail_report(
    SessionDetailReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_report(SessionReport self, SseSerializer serializer);

  @protected
  void sse_encode_session_view(SessionView self, SseSerializer serializer);

  @protected
  void sse_encode_sessions_report(
    SessionsReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_turn_view(TurnView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_report(
    WorkspaceReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_view(WorkspaceView self, SseSerializer serializer);

  @protected
  void sse_encode_workspaces_report(
    WorkspacesReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
