// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/kb.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -345035108;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kb_admin_desktop',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<WorkspaceReport> crateApiKbAddWorkspace({
    required String name,
    required String path,
  });

  Future<SessionDetailReport> crateApiKbAsk({
    required String workspaceId,
    required String sessionId,
    required String turnId,
    required String question,
  });

  Future<String> crateApiKbConfigFilePath();

  Future<ConfigView> crateApiKbConfigViewDefault();

  Future<ConnectReport> crateApiKbConnectReportDefault();

  Future<ConnectReport> crateApiKbConnectTo({required ConnectionView profile});

  Future<String> crateApiKbConnectionKindDescription({required String kind});

  Future<List<String>> crateApiKbConnectionKinds();

  Future<ConnectionState> crateApiKbConnectionState();

  Future<ConnectionState> crateApiKbConnectionStateDefault();

  Future<ConnectionView> crateApiKbConnectionViewDefault();

  Future<SessionReport> crateApiKbCreateSession({
    required String workspaceId,
    required String title,
  });

  Future<void> crateApiKbDisconnect();

  Future<SessionDetailReport> crateApiKbGetSession({
    required String workspaceId,
    required String sessionId,
  });

  Future<SessionsReport> crateApiKbListSessions({required String workspaceId});

  Future<WorkspacesReport> crateApiKbListWorkspaces();

  Future<ConfigView> crateApiKbLoadConfig();

  Future<OpReport> crateApiKbOpReportDefault();

  Future<OpReport> crateApiKbRemoveSession({
    required String workspaceId,
    required String sessionId,
  });

  Future<OpReport> crateApiKbRemoveWorkspace({required String workspaceId});

  Future<String> crateApiKbSaveConfig({
    required String defaultName,
    required List<ConnectionView> connections,
  });

  Future<SessionDetailReport> crateApiKbSessionDetailReportDefault();

  Future<SessionReport> crateApiKbSessionReportDefault();

  Future<SessionView> crateApiKbSessionViewDefault();

  Future<SessionsReport> crateApiKbSessionsReportDefault();

  Future<ConnectionView> crateApiKbSuggestedLocalConnection({
    required String name,
  });

  Future<TurnView> crateApiKbTurnViewDefault();

  Future<WorkspaceReport> crateApiKbWorkspaceReportDefault();

  Future<WorkspaceView> crateApiKbWorkspaceViewDefault();

  Future<WorkspacesReport> crateApiKbWorkspacesReportDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<WorkspaceReport> crateApiKbAddWorkspace({
    required String name,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbAddWorkspaceConstMeta,
        argValues: [name, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbAddWorkspaceConstMeta => const TaskConstMeta(
    debugName: "add_workspace",
    argNames: ["name", "path"],
  );

  @override
  Future<SessionDetailReport> crateApiKbAsk({
    required String workspaceId,
    required String sessionId,
    required String turnId,
    required String question,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(turnId, serializer);
          sse_encode_String(question, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_detail_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbAskConstMeta,
        argValues: [workspaceId, sessionId, turnId, question],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbAskConstMeta => const TaskConstMeta(
    debugName: "ask",
    argNames: ["workspaceId", "sessionId", "turnId", "question"],
  );

  @override
  Future<String> crateApiKbConfigFilePath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConfigFilePathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConfigFilePathConstMeta =>
      const TaskConstMeta(debugName: "config_file_path", argNames: []);

  @override
  Future<ConfigView> crateApiKbConfigViewDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_config_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConfigViewDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConfigViewDefaultConstMeta =>
      const TaskConstMeta(debugName: "config_view_default", argNames: []);

  @override
  Future<ConnectReport> crateApiKbConnectReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connect_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "connect_report_default", argNames: []);

  @override
  Future<ConnectReport> crateApiKbConnectTo({required ConnectionView profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_connection_view(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connect_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectToConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectToConstMeta =>
      const TaskConstMeta(debugName: "connect_to", argNames: ["profile"]);

  @override
  Future<String> crateApiKbConnectionKindDescription({required String kind}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectionKindDescriptionConstMeta,
        argValues: [kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectionKindDescriptionConstMeta =>
      const TaskConstMeta(
        debugName: "connection_kind_description",
        argNames: ["kind"],
      );

  @override
  Future<List<String>> crateApiKbConnectionKinds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectionKindsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectionKindsConstMeta =>
      const TaskConstMeta(debugName: "connection_kinds", argNames: []);

  @override
  Future<ConnectionState> crateApiKbConnectionState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectionStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectionStateConstMeta =>
      const TaskConstMeta(debugName: "connection_state", argNames: []);

  @override
  Future<ConnectionState> crateApiKbConnectionStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectionStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectionStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "connection_state_default", argNames: []);

  @override
  Future<ConnectionView> crateApiKbConnectionViewDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbConnectionViewDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbConnectionViewDefaultConstMeta =>
      const TaskConstMeta(debugName: "connection_view_default", argNames: []);

  @override
  Future<SessionReport> crateApiKbCreateSession({
    required String workspaceId,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbCreateSessionConstMeta,
        argValues: [workspaceId, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbCreateSessionConstMeta => const TaskConstMeta(
    debugName: "create_session",
    argNames: ["workspaceId", "title"],
  );

  @override
  Future<void> crateApiKbDisconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: []);

  @override
  Future<SessionDetailReport> crateApiKbGetSession({
    required String workspaceId,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_detail_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbGetSessionConstMeta,
        argValues: [workspaceId, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbGetSessionConstMeta => const TaskConstMeta(
    debugName: "get_session",
    argNames: ["workspaceId", "sessionId"],
  );

  @override
  Future<SessionsReport> crateApiKbListSessions({required String workspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sessions_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbListSessionsConstMeta,
        argValues: [workspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbListSessionsConstMeta => const TaskConstMeta(
    debugName: "list_sessions",
    argNames: ["workspaceId"],
  );

  @override
  Future<WorkspacesReport> crateApiKbListWorkspaces() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspaces_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbListWorkspacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbListWorkspacesConstMeta =>
      const TaskConstMeta(debugName: "list_workspaces", argNames: []);

  @override
  Future<ConfigView> crateApiKbLoadConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_config_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbLoadConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbLoadConfigConstMeta =>
      const TaskConstMeta(debugName: "load_config", argNames: []);

  @override
  Future<OpReport> crateApiKbOpReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_op_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbOpReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbOpReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "op_report_default", argNames: []);

  @override
  Future<OpReport> crateApiKbRemoveSession({
    required String workspaceId,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_op_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbRemoveSessionConstMeta,
        argValues: [workspaceId, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbRemoveSessionConstMeta => const TaskConstMeta(
    debugName: "remove_session",
    argNames: ["workspaceId", "sessionId"],
  );

  @override
  Future<OpReport> crateApiKbRemoveWorkspace({required String workspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_op_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbRemoveWorkspaceConstMeta,
        argValues: [workspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbRemoveWorkspaceConstMeta => const TaskConstMeta(
    debugName: "remove_workspace",
    argNames: ["workspaceId"],
  );

  @override
  Future<String> crateApiKbSaveConfig({
    required String defaultName,
    required List<ConnectionView> connections,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(defaultName, serializer);
          sse_encode_list_connection_view(connections, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSaveConfigConstMeta,
        argValues: [defaultName, connections],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSaveConfigConstMeta => const TaskConstMeta(
    debugName: "save_config",
    argNames: ["defaultName", "connections"],
  );

  @override
  Future<SessionDetailReport> crateApiKbSessionDetailReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_detail_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSessionDetailReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSessionDetailReportDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "session_detail_report_default",
        argNames: [],
      );

  @override
  Future<SessionReport> crateApiKbSessionReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSessionReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSessionReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "session_report_default", argNames: []);

  @override
  Future<SessionView> crateApiKbSessionViewDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSessionViewDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSessionViewDefaultConstMeta =>
      const TaskConstMeta(debugName: "session_view_default", argNames: []);

  @override
  Future<SessionsReport> crateApiKbSessionsReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sessions_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSessionsReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSessionsReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "sessions_report_default", argNames: []);

  @override
  Future<ConnectionView> crateApiKbSuggestedLocalConnection({
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbSuggestedLocalConnectionConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbSuggestedLocalConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "suggested_local_connection",
        argNames: ["name"],
      );

  @override
  Future<TurnView> crateApiKbTurnViewDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_turn_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbTurnViewDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbTurnViewDefaultConstMeta =>
      const TaskConstMeta(debugName: "turn_view_default", argNames: []);

  @override
  Future<WorkspaceReport> crateApiKbWorkspaceReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbWorkspaceReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbWorkspaceReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "workspace_report_default", argNames: []);

  @override
  Future<WorkspaceView> crateApiKbWorkspaceViewDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbWorkspaceViewDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbWorkspaceViewDefaultConstMeta =>
      const TaskConstMeta(debugName: "workspace_view_default", argNames: []);

  @override
  Future<WorkspacesReport> crateApiKbWorkspacesReportDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspaces_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKbWorkspacesReportDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKbWorkspacesReportDefaultConstMeta =>
      const TaskConstMeta(debugName: "workspaces_report_default", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConnectionView dco_decode_box_autoadd_connection_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connection_view(raw);
  }

  @protected
  ConfigView dco_decode_config_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConfigView(
      path: dco_decode_String(arr[0]),
      exists: dco_decode_bool(arr[1]),
      defaultName: dco_decode_String(arr[2]),
      connections: dco_decode_list_connection_view(arr[3]),
      error: dco_decode_String(arr[4]),
    );
  }

  @protected
  ConnectReport dco_decode_connect_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ConnectReport(
      ok: dco_decode_bool(arr[0]),
      profileName: dco_decode_String(arr[1]),
      serverVersion: dco_decode_String(arr[2]),
      protocolVersion: dco_decode_u_32(arr[3]),
      isLocal: dco_decode_bool(arr[4]),
      launchedPid: dco_decode_u_32(arr[5]),
      error: dco_decode_String(arr[6]),
    );
  }

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConnectionState(
      connected: dco_decode_bool(arr[0]),
      profileName: dco_decode_String(arr[1]),
      serverVersion: dco_decode_String(arr[2]),
      launchedPid: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  ConnectionView dco_decode_connection_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ConnectionView(
      name: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      summary: dco_decode_String(arr[2]),
      kbCore: dco_decode_String(arr[3]),
      runtimeDir: dco_decode_String(arr[4]),
      storageDir: dco_decode_String(arr[5]),
      address: dco_decode_String(arr[6]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConnectionView> dco_decode_list_connection_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_connection_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SessionView> dco_decode_list_session_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_view).toList();
  }

  @protected
  List<TurnView> dco_decode_list_turn_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_turn_view).toList();
  }

  @protected
  List<WorkspaceView> dco_decode_list_workspace_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_workspace_view).toList();
  }

  @protected
  OpReport dco_decode_op_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OpReport(
      ok: dco_decode_bool(arr[0]),
      error: dco_decode_String(arr[1]),
    );
  }

  @protected
  SessionDetailReport dco_decode_session_detail_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionDetailReport(
      ok: dco_decode_bool(arr[0]),
      session: dco_decode_session_view(arr[1]),
      turns: dco_decode_list_turn_view(arr[2]),
      error: dco_decode_String(arr[3]),
    );
  }

  @protected
  SessionReport dco_decode_session_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionReport(
      ok: dco_decode_bool(arr[0]),
      session: dco_decode_session_view(arr[1]),
      error: dco_decode_String(arr[2]),
    );
  }

  @protected
  SessionView dco_decode_session_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SessionView(
      id: dco_decode_String(arr[0]),
      workspaceId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      updatedAtMillis: dco_decode_i_64(arr[3]),
      turnCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  SessionsReport dco_decode_sessions_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionsReport(
      ok: dco_decode_bool(arr[0]),
      sessions: dco_decode_list_session_view(arr[1]),
      error: dco_decode_String(arr[2]),
    );
  }

  @protected
  TurnView dco_decode_turn_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TurnView(
      id: dco_decode_String(arr[0]),
      role: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      reasoning: dco_decode_String(arr[3]),
      state: dco_decode_String(arr[4]),
      notice: dco_decode_String(arr[5]),
      noticeIsError: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceReport dco_decode_workspace_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkspaceReport(
      ok: dco_decode_bool(arr[0]),
      workspace: dco_decode_workspace_view(arr[1]),
      error: dco_decode_String(arr[2]),
    );
  }

  @protected
  WorkspaceView dco_decode_workspace_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkspaceView(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
    );
  }

  @protected
  WorkspacesReport dco_decode_workspaces_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkspacesReport(
      ok: dco_decode_bool(arr[0]),
      workspaces: dco_decode_list_workspace_view(arr[1]),
      error: dco_decode_String(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConnectionView sse_decode_box_autoadd_connection_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connection_view(deserializer));
  }

  @protected
  ConfigView sse_decode_config_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_defaultName = sse_decode_String(deserializer);
    var var_connections = sse_decode_list_connection_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return ConfigView(
      path: var_path,
      exists: var_exists,
      defaultName: var_defaultName,
      connections: var_connections,
      error: var_error,
    );
  }

  @protected
  ConnectReport sse_decode_connect_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_profileName = sse_decode_String(deserializer);
    var var_serverVersion = sse_decode_String(deserializer);
    var var_protocolVersion = sse_decode_u_32(deserializer);
    var var_isLocal = sse_decode_bool(deserializer);
    var var_launchedPid = sse_decode_u_32(deserializer);
    var var_error = sse_decode_String(deserializer);
    return ConnectReport(
      ok: var_ok,
      profileName: var_profileName,
      serverVersion: var_serverVersion,
      protocolVersion: var_protocolVersion,
      isLocal: var_isLocal,
      launchedPid: var_launchedPid,
      error: var_error,
    );
  }

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_profileName = sse_decode_String(deserializer);
    var var_serverVersion = sse_decode_String(deserializer);
    var var_launchedPid = sse_decode_u_32(deserializer);
    return ConnectionState(
      connected: var_connected,
      profileName: var_profileName,
      serverVersion: var_serverVersion,
      launchedPid: var_launchedPid,
    );
  }

  @protected
  ConnectionView sse_decode_connection_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_kbCore = sse_decode_String(deserializer);
    var var_runtimeDir = sse_decode_String(deserializer);
    var var_storageDir = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    return ConnectionView(
      name: var_name,
      kind: var_kind,
      summary: var_summary,
      kbCore: var_kbCore,
      runtimeDir: var_runtimeDir,
      storageDir: var_storageDir,
      address: var_address,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConnectionView> sse_decode_list_connection_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConnectionView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connection_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SessionView> sse_decode_list_session_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<TurnView> sse_decode_list_turn_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TurnView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_turn_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<WorkspaceView> sse_decode_list_workspace_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorkspaceView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_workspace_view(deserializer));
    }
    return ans_;
  }

  @protected
  OpReport sse_decode_op_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    return OpReport(ok: var_ok, error: var_error);
  }

  @protected
  SessionDetailReport sse_decode_session_detail_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_session = sse_decode_session_view(deserializer);
    var var_turns = sse_decode_list_turn_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return SessionDetailReport(
      ok: var_ok,
      session: var_session,
      turns: var_turns,
      error: var_error,
    );
  }

  @protected
  SessionReport sse_decode_session_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_session = sse_decode_session_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return SessionReport(ok: var_ok, session: var_session, error: var_error);
  }

  @protected
  SessionView sse_decode_session_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_updatedAtMillis = sse_decode_i_64(deserializer);
    var var_turnCount = sse_decode_u_32(deserializer);
    return SessionView(
      id: var_id,
      workspaceId: var_workspaceId,
      title: var_title,
      updatedAtMillis: var_updatedAtMillis,
      turnCount: var_turnCount,
    );
  }

  @protected
  SessionsReport sse_decode_sessions_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_sessions = sse_decode_list_session_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return SessionsReport(ok: var_ok, sessions: var_sessions, error: var_error);
  }

  @protected
  TurnView sse_decode_turn_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_reasoning = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_notice = sse_decode_String(deserializer);
    var var_noticeIsError = sse_decode_bool(deserializer);
    return TurnView(
      id: var_id,
      role: var_role,
      text: var_text,
      reasoning: var_reasoning,
      state: var_state,
      notice: var_notice,
      noticeIsError: var_noticeIsError,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceReport sse_decode_workspace_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_workspace = sse_decode_workspace_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return WorkspaceReport(
      ok: var_ok,
      workspace: var_workspace,
      error: var_error,
    );
  }

  @protected
  WorkspaceView sse_decode_workspace_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return WorkspaceView(id: var_id, name: var_name, path: var_path);
  }

  @protected
  WorkspacesReport sse_decode_workspaces_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_workspaces = sse_decode_list_workspace_view(deserializer);
    var var_error = sse_decode_String(deserializer);
    return WorkspacesReport(
      ok: var_ok,
      workspaces: var_workspaces,
      error: var_error,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_connection_view(
    ConnectionView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connection_view(self, serializer);
  }

  @protected
  void sse_encode_config_view(ConfigView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_String(self.defaultName, serializer);
    sse_encode_list_connection_view(self.connections, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_connect_report(ConnectReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.profileName, serializer);
    sse_encode_String(self.serverVersion, serializer);
    sse_encode_u_32(self.protocolVersion, serializer);
    sse_encode_bool(self.isLocal, serializer);
    sse_encode_u_32(self.launchedPid, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_String(self.profileName, serializer);
    sse_encode_String(self.serverVersion, serializer);
    sse_encode_u_32(self.launchedPid, serializer);
  }

  @protected
  void sse_encode_connection_view(
    ConnectionView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.kbCore, serializer);
    sse_encode_String(self.runtimeDir, serializer);
    sse_encode_String(self.storageDir, serializer);
    sse_encode_String(self.address, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_connection_view(
    List<ConnectionView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connection_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_session_view(
    List<SessionView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_turn_view(
    List<TurnView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_turn_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_workspace_view(
    List<WorkspaceView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_workspace_view(item, serializer);
    }
  }

  @protected
  void sse_encode_op_report(OpReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_session_detail_report(
    SessionDetailReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_session_view(self.session, serializer);
    sse_encode_list_turn_view(self.turns, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_session_report(SessionReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_session_view(self.session, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_session_view(SessionView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.workspaceId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.updatedAtMillis, serializer);
    sse_encode_u_32(self.turnCount, serializer);
  }

  @protected
  void sse_encode_sessions_report(
    SessionsReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_list_session_view(self.sessions, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_turn_view(TurnView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.reasoning, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.notice, serializer);
    sse_encode_bool(self.noticeIsError, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_report(
    WorkspaceReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_workspace_view(self.workspace, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_workspace_view(WorkspaceView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_workspaces_report(
    WorkspacesReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_list_workspace_view(self.workspaces, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
